<html>

<head>

<title>Vehicle Brand Master</title>
</head>

<body bgcolor="#FFFFE6">

<form method="POST" action="./DBMastController">

  <p>&nbsp;</p>
  <div align="center">
    <center>
    <table border="1" width="100%" bordercolor="#FFFFE6">
      <tr>
        <td width="100%">
          <p align="center"><b><font face="Verdana" color="#820082" size="2">Dealer
          Branch
          Information Form</font></b></p>
        </td>
      </tr>
    </table>
    </center>
  </div>
  <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#820082">
        <p align="center"><b><font size="1"><font color="#FFFFE6"><font face="Verdana">
        <marquee direction="right" align="middle" behavior="slide">Vehicle
        Dealer Management</marquee>
        </font></font></font></b></td>
    </tr>
  </table>
  <div align="right">
    <table border="1" width="10%" bordercolor="#FFFFE6">
      <tr>
        <td width="100%">
          <p align="right">&nbsp;</td>
      </tr>
    </table>
  </div>
  <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </p>
  <div align="center">
    <table border="0" width="60%" cellspacing="0" cellpadding="0">
      <tr>
        <td width="25%">
          <p align="right"><input type="submit" value="AddNew" name="submit" style="color: #660066"></td>
        <center>
        <td width="25%">
          <p align="center"><input type="submit" value="View" name="submit" style="color: #660066"></td>
        </center>
        <td width="20%">
          <p align="left"><input type="submit" value="Delete" name="submit" style="color: #660066"></td>
        <center>
        <td width="25%"><input type="submit" value="Update" name="submit" style="color: #660066"></td>
        </tr>
      </table>
    </center>
  </div>



</form>

</body>

</html>
