<%@ page language="java"%>
<%@ page import="java.sql.*,java.io.*"%>
<html>
<head>
<title>Dealer Manufacture Form</title>
</head>
<body bgcolor="#FFFFE6" topmargin=0 leftmargin=0>
<form method="POST" action="./dmController">   
  <%@ include file="header.htm"%>
  
  
  </p>  
  <p>&nbsp;</p>  
  <p>&nbsp;</p>
  <p>&nbsp;</p>  
  <center><input type="submit" value="Addnew" name="submit" style="color: #660066">
  <input type="submit" value="Delete" name="submit" style="color: #660066">
  <input type="submit" value="View" name="submit" style="color: #660066"></center>
</form>
</body>
</html>
