<html>

<head>

<title>Vehicle Brand Master</title>
</head>

<body bgcolor="#FFFFE6" topmargin=0 leftmargin=0>

<form method="POST" action="./DepartmentController">
 
  <%@ include file="header.htm"%>    
  <p>&nbsp;</p>
    <p>&nbsp;</p>
	  <p>&nbsp;</p>
	    <p>&nbsp;</p>		 
   <center><input type="submit" value="AddNew" name="submit" style="color: #660066">
        
        
          <input type="submit" value="View" name="submit" style="color: #660066">
        
        
          <input type="submit" value="Delete" name="submit" style="color: #660066"></center>
       
        


</form>

</body>

</html>
