<html>
<head>
<title>Employee Information</title>
</head>
<body bgcolor="#FFFFE6" topmargin=0 leftmargin=0>
<form method="POST" action="--WEBBOT-SELF--"> 
 <%@ include file="header.htm"%>
 
 <p>&nbsp;</p>
 
 <div align="center">
    <center>
    <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#FFFFE6">
        <p align="center"><b><font face="Verdana" color="#660066" size="2">Employee
        Information</font></b></td>
    </tr>
  </table>
    </center>
  </div> 
 
 <div align="right">
  <table border="0" width="60%">
    <tr>
      <td width="100%" align="left"><a href="employee_mast_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold"><u>Employee
        Information</u></a></td>
    </tr>
    <tr>
      <td width="100%" align="left"><a href="Depart_master_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold"><u>Department
        Information</u></a></td>
    </tr>
    <tr>
      <td width="100%" align="left"><a href="designation_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold"><u>Designation
        Information</u></a></td>
    </tr>
    <tr>
      <td width="100%" align="left"><a href="prof_mast_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold"><u>Profile
        Information</u></a></td>
    </tr>
    <tr>
      <td width="100%" align="left"><a href="prof_emp_mast_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold"><u>Profile
        Employee Information</u></a></td>
    </tr>
  </table>
 </div>
</form>

</body>

</html>
