<html>

<head>

<title>Vehicle Brand Master</title>
</head>

<body bgcolor="#FFFFE6">

<form method="POST" action="--WEBBOT-SELF--">

  <p>&nbsp;</p>
  <div align="center">
    <center>
    <table border="1" width="100%" bordercolor="#FFFFE6">
      <tr>
        <td width="100%">
          <p align="center"><b><font face="Verdana" color="#820082" size="2">Employee
          Information Form</font></b></p>
        </td>
      </tr>
    </table>
    </center>
  </div>
  <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#820082">
        <p align="center"><b><font size="1"><font color="#FFFFE6"><font face="Verdana">
        <marquee direction="right" align="middle" behavior="slide">Vehicle
        Dealer Management</marquee>
        </font></font></font></b></td>
    </tr>
  </table>
  <div align="right">
    <table border="1" width="10%" bordercolor="#FFFFE6">
      <tr>
        <td width="100%">
          <p align="right"><font color="#820082" size="1">Back</font></td>
      </tr>
    </table>
  </div>
  <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
  <div align="center">
    <center>
    <table border="0" width="100%" height="599">
      <tr>
        <td width="50%" align="right" height="25"><font color="#820082" size="1">Employee
          Id</font></td>
        <td width="50%" height="25"><select size="1" name="did">
          </select></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font color="#820082" size="1">Employee
          First Name</font></td>
        <td width="50%" height="25"><input type="text" name="T15" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font color="#820082" size="1">Employee
          Middle Name</font></td>
        <td width="50%" height="25"><input type="text" name="T16" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font color="#820082" size="1">Employee
          Last Name</font></td>
        <td width="50%" height="25"><input type="text" name="T1" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Date
          of Birth</font></td>
        <td width="50%" height="25"><input type="text" name="T2" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Date
          of Join</font></td>
        <td width="50%" height="25"><input type="text" name="T3" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">(Address)
          H.No.</font></td>
        <td width="50%" height="25"><input type="text" name="T4" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Street</font></td>
        <td width="50%" height="25"><input type="text" name="T5" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">City</font></td>
        <td width="50%" height="25"><input type="text" name="T6" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">State</font></td>
        <td width="50%" height="25"><input type="text" name="T7" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Country</font></td>
        <td width="50%" height="25"><input type="text" name="T8" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Zip
          Code</font></td>
        <td width="50%" height="25"><input type="text" name="T9" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Home
          Phone</font></td>
        <td width="50%" height="25"><input type="text" name="T10" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Work
          Phone</font></td>
        <td width="50%" height="25"><input type="text" name="T11" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Mobile
          Phone</font></td>
        <td width="50%" height="25"><input type="text" name="T12" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Email
          Id1</font></td>
        <td width="50%" height="25"><input type="text" name="T13" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Email
          Id 2</font></td>
        <td width="50%" height="25"><input type="text" name="T14" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="24"><font size="1" color="#820082">Gender</font></td>
        <td width="50%" height="24"><input type="text" name="T19" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="24"><font size="1" color="#820082">Department
          Id</font></td>
        <td width="50%" height="24"><input type="text" name="T17" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right" height="25"><font size="1" color="#820082">Designation
          Id</font> </td>
        <td width="50%" height="25"><input type="text" name="T18" size="20"></td>
      </tr>
      <tr>
        <td width="50%" height="103">&nbsp;
          <p>&nbsp;</p>
        </center>
        <p align="right">&nbsp;</td>
      <center>
      <td width="50%" height="103"></td>
      </tr>
    </table>
    </center>
  </div>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</form>

</body>

</html>
