<html>

<head>

<title>Welcome to Online Vehicle Dealership Management</title>
</head>

<body bgcolor="#FFFFE6">

<form method="POST" action="AdminLogin.jsp">

  
  <p>&nbsp;</p>
  <div align="center">
    <center>
    <table border="0" width="100%" >
      <tr>
        <td width="100%">
          <p align="center"><font color="#800080" face="Monotype Corsiva" size="5"><b>Welcome
          to Online Vehicle Dealership Management</b></font></td>
      </tr>
    </table>
    </center>
  </div>
  <p>&nbsp;</p>
  <div align="center">
    <table border="0" width="100%">
      <tr>
        <td width="100%">
          <p style="word-spacing: 0; margin: 0" align="left"><font color="#FF0000" size="2">Invalid
          Login Id or Password.</font></p>
          <p style="word-spacing: 0; margin: 0" align="left"><font color="#FF0000" size="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          Please Enter Correct Login Id/Password....</font></td>
      </tr>
    </table>
  </div>
  <div align="right">
    <table border="1" width="50%" style="color: #800080" height="80" bgcolor="#FFFFE6" bordercolor="#FFFFE6" cellspacing="0" cellpadding="0">
      <tr>
        <td width="30%" align="right"><font face="Verdana" color="#800080" size="2">Login
          Id</font></td>
        <td width="50%"><input type="text" name="lid" size="20"></td>
      </tr>
      <tr>
        <td width="30%" align="right"><font face="Verdana" color="#800080" size="2">Password</font></td>
        <td width="50%"><input type="password" name="pwd" size="20"></td>
      </tr>
      <tr>
        <td width="30%" align="right">&nbsp;</td>
        <td width="50%">&nbsp;
          <p><input type="submit" value="Proceed" name="submit" style="color: #800080"></td>
      </tr>
    </table>
  </div>
  <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </p>
  
</form>

</body>

</html>
