<%@page language="java"%> 
<HTML>
<HEAD>
<TITLE> New Document </TITLE>

</HEAD>

<body bgcolor="#FFFFE6" topmargin=0 leftmargin=0> 
<table border="0" width="100%" bgcolor="#820082" style="color: #FFFFE6" height="30">
  <tr>
    <td width="40%" height="26">
      <p align="center"><dfn><font size="1" face="Monotype Corsiva"><marquee width="671" height="23" style="font-size: 14pt" align="middle">About
      Us
      </marquee></font></dfn></p>
    </td>
  </tr>
</table>
<p> </p>
<p> </p>
<p> </p>
<p> </p>

<table border="0"  width=100%>
<tr>
		<td align="center" width=100%   colspan="2"></td>
</tr>
<tr>
		<td width=20% ><%@ include file="navigation.jsp"%></td>
		<td align="Center" ><BR>
		<table ><tr><td><CENTER><B><P><i><font face="Garamond" color="#820082" size="3">The system design aims at managing dealership transactions of an automobile company.  This design involves the maintenance of the different branches located at various locations and their transactions with the head quarters.  This System maintains the details of manufacturers of the vehicles along with their types and make.</font></i></B></CENTER></td></tr></table></td>
</tr>
</table>


</BODY>
</HTML>
