<html>
<head>
<title>Purchase Information Module</title>
</head>
<body bgcolor="#FFFFE6" topmargin=0 leftmargin=0>
<form method="POST" action="--WEBBOT-SELF--"> 
<%@ include file="header.htm"%> 
 
<p>&nbsp;</p>
 
 <div align="center">
    <center>
    <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#FFFFE6">
        <p align="center"><b><font face="Verdana" color="#660066" size="2">Purchase Information
        Module</font></b></td>
    </tr>
  </table>
    </center>
  </div>  
  
 <div align="right">
  <table border="0" width="60%">
    <tr>
      <td width="100%" align="left"><a href="purchase_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold"><u>Purchase
        Information</u></a></td>
    </tr>
    <tr>
      <td width="100%" align="left"><a href="purchase_details_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold"><u>Purchase
        Details Information</u></a></td>
    </tr>
    <tr>
      <td width="100%" align="left"><a href="inventery_record_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold"><u>Inventory&nbsp;
        Record Information</u></a></td>
    </tr>
  </table>
 </div>
</form>

</body>

</html>
