<html>

<head>

<title>Vehicle Brand Master</title>
</head>

<body bgcolor="#FFFFE6" topmargin=0 leftmargin=0>

<form method="POST" action="./SalesMastController">
<%@ include file="header.htm"%>
  
 
<p>&nbsp;</p>
  
 
  <div align="center">
    <center>
    <table border="1" width="100%" bordercolor="#FFFFE6">
      <tr>
        <td width="100%">
          <p align="center"><b><font face="Verdana" color="#820082" size="2">Sales Information&nbsp;</font></b></p>
          <p align="center">&nbsp;</p>
        </td>
      </tr>
    </table>
    </center>
  </div>
  
  <div align="right">
    <table border="1" width="10%" bordercolor="#FFFFE6">
      <tr>
        <td width="100%">
          <p align="right">&nbsp;</td>
      </tr>
    </table>
  </div>
  <div align="center">
    <table border="0" width="60%" cellspacing="0" cellpadding="0">
      <tr>
        <td width="25%">
          <p align="right"><input type="submit" value="AddNew" name="submit" style="color: #660066"></td>
        <center>
        <td width="15%">
          <p align="center"><input type="submit" value="View" name="submit" style="color: #660066"></td>
        </center>
        <td width="20%">
          <p align="left"><input type="submit" value="Delete" name="submit" style="color: #660066"></td>
        <center>
        </tr>
      </table>
    </center>
  </div>
  
</form>

</body>

</html>
