<html>

<head>

<title>Result Form</title>
</head>

<body bgcolor="#FFFFE6" topmargin=0 leftmargin=0>

<form method="POST" action="--WEBBOT-SELF--">
  
 
  
  <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#820082">
        <p align="center">
  
 
  
  <center><b><font color="#FFFFE6"><font face="Verdana" size="3" >Sub Brand Fue</font></font><font face="Verdana" color="#FFFFE6" size="3" >l
  System Information&nbsp;</font></b></center>
      </td>
    </tr>
  </table>
 <div align="right">
    <table border="1" width="10%" bordercolor="#FFFFE6">
      <tr>
        <td width="100%">
          <p align="right"><font color="#820082" size="1"><a href="sub_br_fuel_sys_mast_home.jsp">Back</a></font></td>
      </tr>
    </table>
  </div>
  <p>&nbsp;</p>
  <table border="0" width="100%">
    <tr>
      <td width="50%" align="right"><b><font color="#820082" size="2">Your
        Information is Added into the Database </font></b></td>
      <td width="50%"></td>
    </tr>
    <tr>
      <td width="50%" align="right">
        
        <p>&nbsp;</p>
        <p>&nbsp;</p>
      </td>
      <td width="50%"></td>
    </tr>
  </table>
</form>

</body>

</html>
