<html>

<head>

<title>Vehicle Brand Master</title>
</head>

<body bgcolor="#FFFFE6" topmargin=0 leftmargin=0>

<form method="POST" action="./SubBrdFuelMastController">
 
  <%@ include file="header.htm"%>  
  <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#FFFFE6">
        <p align="center">&nbsp;
        <p align="center"><b><font face="Verdana" color="#820082" size="2">Sub
          Brand Fuel Information&nbsp;</font></b></td>
    </tr>
  </table>
  <div align="right">
    <table border="1" width="10%" bordercolor="#FFFFE6">
      <tr>
        <td width="100%">
          <p align="right">&nbsp;</td>
      </tr>
    </table>
  </div>
  <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </p>
  <div align="center">
    <table border="0" width="45%" cellspacing="0" cellpadding="0">
      <tr>
        <td width="15%">
          <p align="right"><input type="submit" value="AddNew" name="submit" style="color: #660066"></td>
        <center>
        <td width="15%">
          <p align="center"><input type="submit" value="View" name="submit" style="color: #660066"></td>
        </center>
        <td width="15%">
          <p align="left"><input type="submit" value="Delete" name="submit" style="color: #660066"></td>
       
        </tr>
      </table>
    </center>
  </div>


 
</form>

</body>

</html>
