<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Vehicle Brand Manufacture Insert</title>
</head>

<body bgcolor="#FF00FF">

<form method="POST" action="--WEBBOT-SELF--">
  <!--webbot bot="SaveResults" U-File="F:\vdm\_private\form_results.txt"
  S-Format="TEXT/CSV" S-Label-Fields="TRUE" -->
  <table border="1" width="100%">
    <tr>
      <td width="100%">
        <p align="center"><font face="Verdana" size="2" color="#800000"><b>Vehicle
        Brand Manufacture Insert</b></font></td>
    </tr>
  </table>
  <p>&nbsp;</p>
  <table border="1" width="100%">
    <tr>
      <td width="50%" align="right"><font color="#800000" face="Verdana" size="2"><b>Vehicle
        Manufacture ID</b></font></td>
      <td width="50%"><select size="1" name="D1">
        </select></td>
    </tr>
    <tr>
      <td width="50%" align="right"><font color="#800000" face="Verdana" size="2"><b>Brand
        ID</b></font></td>
      <td width="50%"><select size="1" name="D2">
        </select></td>
    </tr>
    <tr>
      <td width="50%" align="right">&nbsp;
        <p>&nbsp;</p>
        <p><font color="#800000" face="Verdana" size="2"><b><input type="submit" value="Insert" name="submit" style="color: #FF00FF"></b></font></td>
      <td width="50%">&nbsp;</td>
    </tr>
  </table>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</form>

</body>

</html>
