<html>
<head>
<title>Vehicle Brand Master</title>
</head>
<body bgcolor="#FFECFF">
<form method="POST" action="--WEBBOT-SELF--">
    <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#660066">
        <p align="center"><b><font face="Verdana" size="3" color="#FFD9FF">Vehicle
        Brand Master</font></b></td>
    </tr>
  </table>
  <p>&nbsp;</p>
  <div align="center">
    <center>
    <table border="0" width="100%">
      <tr>
        <td width="50%" align="right">Brand Id</td>
        <td width="50%"><select size="1" name="D1">
          </select></td>
      </tr>
      <tr>
        <td width="50%" align="right">Brand Name</td>
        <td width="50%"><input type="text" name="T1" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right">Brand Description </td>
        <td width="50%"><textarea rows="2" name="S1" cols="20"></textarea></td>
      </tr>
      <tr>
        <td width="50%">&nbsp;
          <p>&nbsp;</p>
        </center>
        <p align="right"><input type="submit" value="Insert" name="submit"></td>
      <center>
      <td width="50%"></td>
      </tr>
    </table>
    </center>
  </div>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</form>

</body>

</html>
