<html>
<head>
<title>Vehicle Brand Manufacture Module</title>
</head>
<body bgcolor="#FFFFE6" topmargin=0 leftmargin=0>
<form method="POST" action="--WEBBOT-SELF--"> 
<%@ include file="header.htm"%>

<p>&nbsp;</p>

 <div align="center">
    <center>
    <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#FFFFE6">
        <p align="center"><b><font face="Verdana" color="#660066" size="2">Vehicle Brand Manufacture Module</font></b></td>
    </tr>
  </table>
    </center>
  </div>  
  
 <div align="right">
  <table border="0" width="60%">
    <tr>
      <td width="100%" align="left"><a href="vehicle_color_mast_home.jsp" style="font-family: Verdana; font-size: 10pt; color: #660066; font-weight: bold">Vehicle
        Color Master</a></td>
    </tr>
    <tr>
      <td width="100%" align="left"><a href="sub_br_color_mast_home.jsp" style="font-family: Verdana; font-size: 10pt; color: #660066; font-weight: bold">Vehicle
        Sub Brand Color Master</a></td>
    </tr>
  </table>
 </div>
</form>

</body>

</html>
