<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Vehicle Brand Master</title>
</head>

<body bgcolor="#FFFFE6">

<form method="POST" action="--WEBBOT-SELF--">
  <!--webbot bot="SaveResults"
  U-File="F:\vdmscripts\forms\_private\form_results.txt" S-Format="TEXT/CSV"
  S-Label-Fields="TRUE" -->
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#77003C">
        <p align="center"><b><font face="Verdana" size="3" color="#FFFFE6">Vehicle
        Brand Master</font></b></td>
    </tr>
  </table>
  <p>&nbsp;</p>
  <div align="center">
    <center>
    <table border="0" width="100%">
      <tr>
        <td width="50%" align="right"><font color="#77003C">Brand Id</font></td>
        <td width="50%"><select size="1" name="D1">
          </select></td>
      </tr>
      <tr>
        <td width="50%" align="right"><font color="#77003C">Brand Name</font></td>
        <td width="50%"><input type="text" name="T1" size="20"></td>
      </tr>
      <tr>
        <td width="50%" align="right"><font color="#77003C">Brand Description</font> </td>
        <td width="50%"><textarea rows="2" name="S1" cols="20"></textarea></td>
      </tr>
      <tr>
        <td width="50%">&nbsp;
          <p>&nbsp;</p>
        </center>
        <p align="right"><input type="submit" value="Insert" name="submit" style="color: #660066"></td>
      <center>
      <td width="50%"></td>
      </tr>
    </table>
    </center>
  </div>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <p>&nbsp;</p>
</form>

</body>

</html>
