<html>
<head>
<title>Purchase Information Module</title>
</head>
<body bgcolor="#FFFFE6">
<form method="POST" action="--WEBBOT-SELF--">  
 <div align="center">
    <center>
    <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#820082">
        <p align="center"><b><font face="Verdana" size="3" color="#FFFFE6">Purchase Information
        Module </font></b></td>
    </tr>
  </table>
    </center>
  </div>  
  <p>&nbsp;</p>
  <table border="0" width="100%">
    <tr>
      <td width="100%" align="center"><a href="purchase_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Purchase
        Information</a></td>
    </tr>
    <tr>
      <td width="100%" align="center"><a style="color: #800000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </a><a href="purchase_details_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Purchase
        Details Information</a></td>
    </tr>
    <tr>
      <td width="100%" align="center"><a style="color: #800000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </a><a href="inventery_record_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Inventory&nbsp;
        Record Information</a></td>
    </tr>
  </table>
</form>

</body>

</html>
