<html>
<head>
<title>Employee Information</title>
</head>
<body bgcolor="#FFFFE6">
<form method="POST" action="--WEBBOT-SELF--"> 
 <div align="center">
    <center>
    <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#820082">
        <p align="center"><b><font face="Verdana" size="3" color="#FFFFE6">Employee
        Information </font></b></td>
    </tr>
  </table>
    </center>
  </div>  
  <p>&nbsp;</p>
  <p>&nbsp;</p>
  <table border="0" width="100%">
    <tr>
      <td width="100%" align="center"><a style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">&nbsp;&nbsp;&nbsp;
        </a><a href="employee_mast_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Employee
        Information</a></td>
    </tr>
    <tr>
      <td width="100%" align="center"><a style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </a><a href="Depart_master_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Department
        Information</a></td>
    </tr>
    <tr>
      <td width="100%" align="center"><a style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </a><a href="designation_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Designation
        Information</a></td>
    </tr>
    <tr>
      <td width="100%" align="center"><a href="prof_mast_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Profile
        Information</a></td>
    </tr>
    <tr>
      <td width="100%" align="center"><a style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </a><a href="prof_emp_mast_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Profile
        Employee Information</a></td>
    </tr>
  </table>
</form>

</body>

</html>
