<html>
<head>
<title>Sales Module</title>
</head>
<body bgcolor="#FFFFE6">
<form method="POST" action="--WEBBOT-SELF--">  
 <div align="center">
    <center>
    <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#820082">
        <p align="center"><b><font face="Verdana" size="3" color="#FFFFE6">Sales
        Module </font></b></td>
    </tr>
  </table>
    </center>
  </div>  
  <p>&nbsp;</p>
  <table border="0" width="100%">
    <tr>
      <td width="100%" align="center"><a href="sales_mast_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Sales
        Information</a></td>
    </tr>
    <tr>
      <td width="100%" align="center"><a style="color: #800000">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </a><a href="sales_home.jsp" style="color: #660066; font-family: Verdana; font-size: 10pt; font-weight: bold">Sales Details
        Information</a></td>
    </tr>
    <tr>
      <td width="100%" align="center"></td>
    </tr>
  </table>
</form>
</body>
</html>