<html>
<head>
<title>Vehicle Brand Manufacture Module</title>
</head>
<body bgcolor="#FFFFE6">
<form method="POST" action="--WEBBOT-SELF--"> 
 <div align="center">
    <center>
    <table border="0" width="100%" color="" height="30">
    <tr>
      <td width="100%" bgcolor="#820082">
        <p align="center"><b><font face="Verdana" size="3" color="#FFFFE6">Vehicle Brand Manufacture Module </font></b></td>
    </tr>
  </table>
    </center>
  </div>  
  <p>&nbsp;</p>
  <table border="0" width="100%">
    <tr>
      <td width="100%" align="center"><a href="vehicle_color_mast_home.jsp" style="font-family: Verdana; font-size: 10pt; color: #660066; font-weight: bold">Vehicle
        Color Master</a></td>
    </tr>
    <tr>
      <td width="100%" align="center"><a style="font-family: Verdana; font-size: 10pt; color: #660066; font-weight: bold">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </a><a href="sub_br_color_mast_home.jsp" style="font-family: Verdana; font-size: 10pt; color: #660066; font-weight: bold">Vehicle
        Sub Brand Color Master</a></td>
    </tr>
  </table>
</form>

</body>

</html>
