create table vehicle_manufa_master(veh_manu_id number(6) constraint
pk_vid primary key,
manufa_name varchar2(30),
manufact_dno varchar2(30),
manufact_street varchar2(30),
manufact_city varchar2(30),
manufact_state varchar2(30),
manufact_country varchar2(30),
manufact_zip number(8),
manufact_phone1 number(15),
manufact_phone2 number(15),
manufact_fax number(15),
manufact_email varchar2(30))
/
